# NebulaGraph Storaged Configuration (for Docker)
--local_ip=nebula-storaged
--port=9779
--ws_http_port=19779
--ws_h2_port=19780
--meta_server_addrs=nebula-metad:9559
--local_config=true
--data_path=/data/storage
--log_dir=/logs
--v=0
--minloglevel=0
--logtimeformat=true
