#!/bin/bash
# hermes-config-bridge.sh — translates openclaw.json → ~/.hermes/config.yaml + .env
#
# Bridge-owned keys (rewritten every run):
#   config.yaml: model, matrix, platforms
#   .env:        MATRIX_*, GLM_* / LM_* (provider-specific LLM keys)
#
# Non-bridge-owned keys are preserved across re-runs.
set -euo pipefail

OPENCLAW_JSON="${1:-${HOME}/hiclaw-fs/agents/${HICLAW_WORKER_NAME}/openclaw.json}"
HERMES_DIR="${HOME}/.hermes"
CONFIG_YAML="${HERMES_DIR}/config.yaml"
ENV_FILE="${HERMES_DIR}/.env"

if [ ! -f "$OPENCLAW_JSON" ]; then
    echo "[hermes-bridge] ERROR: openclaw.json not found at $OPENCLAW_JSON" >&2
    exit 1
fi

mkdir -p "$HERMES_DIR"

# Extract Matrix values from openclaw.json
MATRIX_HOMESERVER=$(jq -r '.channels.matrix.homeserver // empty' "$OPENCLAW_JSON")
MATRIX_TOKEN=$(jq -r '.channels.matrix.accessToken // empty' "$OPENCLAW_JSON")

# Derive Matrix user_id from worker name + homeserver domain
# (openclaw.json doesn't store userId explicitly; hermes gateway needs it)
MATRIX_DOMAIN=$(echo "$MATRIX_HOMESERVER" | sed 's|https\?://||; s|:[0-9]*||; s|/.*||')
MATRIX_USER="@${HICLAW_WORKER_NAME}:${MATRIX_DOMAIN}"

# Extract LLM provider info from openclaw.json
# openclaw.json structure:
#   .agents.defaults.model.primary = "hiclaw-gateway/glm-5.2"  (provider/model_id)
#   .models.providers.<provider>.baseUrl / .apiKey / .api
MODEL_PRIMARY=$(jq -r '.agents.defaults.model.primary // empty' "$OPENCLAW_JSON")
OC_PROVIDER="${MODEL_PRIMARY%%/*}"
LLM_MODEL="${MODEL_PRIMARY#*/}"

# If primary model not set or doesn't contain "/", try first provider's first model
if [ -z "$OC_PROVIDER" ] || [ "$OC_PROVIDER" = "$LLM_MODEL" ] || [ -z "$LLM_MODEL" ]; then
    OC_PROVIDER=$(jq -r '.models.providers | keys[0] // empty' "$OPENCLAW_JSON")
    LLM_MODEL=$(jq -r --arg p "$OC_PROVIDER" \
        '.models.providers[$p].models[0].id // .models.providers[$p].models[0].name // empty' \
        "$OPENCLAW_JSON")
fi

LLM_BASE_URL=$(jq -r --arg p "$OC_PROVIDER" '.models.providers[$p].baseUrl // empty' "$OPENCLAW_JSON")
LLM_API_KEY=$(jq -r --arg p "$OC_PROVIDER" '.models.providers[$p].apiKey // empty' "$OPENCLAW_JSON")

# Map openclaw model → hermes built-in provider
# GLM models  → zai provider  (GLM_API_KEY + GLM_BASE_URL env vars)
# Other models → lmstudio provider (LM_API_KEY + LM_BASE_URL env vars, generic OpenAI-compatible)
HERMES_PROVIDER=""
LLM_KEY_ENV=""
LLM_BASE_URL_ENV=""

case "$LLM_MODEL" in
    glm-*)
        HERMES_PROVIDER="zai"
        LLM_KEY_ENV="GLM_API_KEY"
        LLM_BASE_URL_ENV="GLM_BASE_URL"
        ;;
    *)
        HERMES_PROVIDER="lmstudio"
        LLM_KEY_ENV="LM_API_KEY"
        LLM_BASE_URL_ENV="LM_BASE_URL"
        ;;
esac

# --- Generate config.yaml (bridge-owned blocks) ---
PRESERVED_YAML=""
if [ -f "$CONFIG_YAML" ]; then
    PRESERVED_YAML=$(python3 -c "
import yaml, sys
try:
    with open('$CONFIG_YAML') as f:
        data = yaml.safe_load(f) or {}
except Exception:
    sys.exit(0)
bridge_keys = {'model', 'matrix', 'platforms', 'approvals', 'agent', 'custom_providers', 'providers'}
preserved = {k: v for k, v in data.items() if k not in bridge_keys}
if preserved:
    print(yaml.dump(preserved, default_flow_style=False, allow_unicode=True))
" 2>/dev/null || true)
fi

cat > "$CONFIG_YAML" << YAML
# Generated by hermes-config-bridge.sh — do not edit bridge-owned sections.
# Bridge-owned: model, matrix, platforms, approvals
model: ${HERMES_PROVIDER}/${LLM_MODEL}

matrix:
  homeserver: ${MATRIX_HOMESERVER}
  user_id: "${MATRIX_USER}"
  access_token: ${MATRIX_TOKEN}

platforms:
  matrix:
    homeserver: ${MATRIX_HOMESERVER}
    user_id: "${MATRIX_USER}"
    access_token: ${MATRIX_TOKEN}

# Auto-approve all terminal commands — headless worker has no user to prompt
approvals:
  mode: "off"
  cron_mode: approve

# Limit agent turns for headless worker.
# Default 15 (graph-worker); analytics-worker overrides to 25 via HERMES_MAX_TURNS
# for the multi-step SOUL.md workflow (read spec → generate nGQL → execute →
# write result.md → write result.json → sync MinIO → notify).
agent:
  max_turns: ${HERMES_MAX_TURNS:-15}
YAML

if [ -n "$PRESERVED_YAML" ]; then
    echo "" >> "$CONFIG_YAML"
    echo "# Preserved non-bridge-owned keys:" >> "$CONFIG_YAML"
    echo "$PRESERVED_YAML" >> "$CONFIG_YAML"
fi

# --- Generate .env (bridge-owned: MATRIX_*, LLM provider keys) ---
TMP_ENV=$(mktemp)
{
    echo "# Bridge-owned (rewritten every run)"
    echo "MATRIX_HOMESERVER=${MATRIX_HOMESERVER}"
    echo "MATRIX_USER_ID=${MATRIX_USER}"
    echo "MATRIX_ACCESS_TOKEN=${MATRIX_TOKEN}"
    echo "GATEWAY_ALLOW_ALL_USERS=true"
    echo "${LLM_KEY_ENV}=${LLM_API_KEY}"
    echo "${LLM_BASE_URL_ENV}=${LLM_BASE_URL}"
    if [ -f "$ENV_FILE" ]; then
        echo ""
        echo "# Preserved non-bridge-owned vars:"
        grep -vE '^(MATRIX_|GLM_|LM_|OPENAI_|GATEWAY_|#)' "$ENV_FILE" 2>/dev/null || true
    fi
} > "$TMP_ENV"
mv "$TMP_ENV" "$ENV_FILE"

echo "[hermes-bridge] config.yaml and .env generated for ${HICLAW_WORKER_NAME} (provider: ${HERMES_PROVIDER}, model: ${LLM_MODEL})"
