#!/bin/bash
# hermes-config-bridge.sh — translates openclaw.json → ~/.hermes/config.yaml + .env
#
# Bridge-owned keys (rewritten every run):
#   config.yaml: model, matrix, platforms.matrix
#   .env:        MATRIX_*, OPENAI_*
#
# Non-bridge-owned keys are preserved across re-runs.
set -euo pipefail

OPENCLAW_JSON="${1:-${HOME}/hiclaw-fs/agents/${HICLAW_WORKER_NAME}/openclaw.json}"
HERMES_DIR="${HOME}/.hermes"
CONFIG_YAML="${HERMES_DIR}/config.yaml"
ENV_FILE="${HERMES_DIR}/.env"

if [ ! -f "$OPENCLAW_JSON" ]; then
    echo "[hermes-bridge] ERROR: openclaw.json not found at $OPENCLAW_JSON" >&2
    exit 1
fi

mkdir -p "$HERMES_DIR"

# Extract values from openclaw.json using jq
MATRIX_HOMESERVER=$(jq -r '.channels.matrix.homeserver // empty' "$OPENCLAW_JSON")
MATRIX_USER=$(jq -r '.channels.matrix.userId // .channels.matrix.user // empty' "$OPENCLAW_JSON")
MATRIX_TOKEN=$(jq -r '.channels.matrix.accessToken // empty' "$OPENCLAW_JSON")
MODEL_PROVIDER=$(jq -r '.model.provider // empty' "$OPENCLAW_JSON")
MODEL_NAME=$(jq -r '.model.model // .model.name // empty' "$OPENCLAW_JSON")
OPENAI_BASE_URL=$(jq -r '.model.baseUrl // empty' "$OPENCLAW_JSON")
OPENAI_API_KEY=$(jq -r '.model.apiKey // .model.openaiApiKey // empty' "$OPENCLAW_JSON")

# --- Generate config.yaml (bridge-owned blocks) ---
PRESERVED_YAML=""
if [ -f "$CONFIG_YAML" ]; then
    PRESERVED_YAML=$(python3 -c "
import yaml, sys
try:
    with open('$CONFIG_YAML') as f:
        data = yaml.safe_load(f) or {}
except Exception:
    sys.exit(0)
bridge_keys = {'model', 'matrix', 'platforms'}
preserved = {k: v for k, v in data.items() if k not in bridge_keys}
if preserved:
    print(yaml.dump(preserved, default_flow_style=False, allow_unicode=True))
" 2>/dev/null || true)
fi

cat > "$CONFIG_YAML" << YAML
# Generated by hermes-config-bridge.sh — do not edit bridge-owned sections.
# Bridge-owned: model, matrix, platforms.matrix
model:
  provider: ${MODEL_PROVIDER}
  name: ${MODEL_NAME}

matrix:
  homeserver: ${MATRIX_HOMESERVER}
  user_id: ${MATRIX_USER}
  access_token: ${MATRIX_TOKEN}

platforms:
  matrix:
    homeserver: ${MATRIX_HOMESERVER}
    user_id: ${MATRIX_USER}
    access_token: ${MATRIX_TOKEN}
YAML

if [ -n "$PRESERVED_YAML" ]; then
    echo "" >> "$CONFIG_YAML"
    echo "# Preserved non-bridge-owned keys:" >> "$CONFIG_YAML"
    echo "$PRESERVED_YAML" >> "$CONFIG_YAML"
fi

# --- Generate .env (bridge-owned: MATRIX_*, OPENAI_*) ---
TMP_ENV=$(mktemp)
{
    echo "# Bridge-owned (rewritten every run)"
    echo "MATRIX_HOMESERVER=${MATRIX_HOMESERVER}"
    echo "MATRIX_USER_ID=${MATRIX_USER}"
    echo "MATRIX_ACCESS_TOKEN=${MATRIX_TOKEN}"
    echo "OPENAI_BASE_URL=${OPENAI_BASE_URL}"
    echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
    if [ -f "$ENV_FILE" ]; then
        echo ""
        echo "# Preserved non-bridge-owned vars:"
        grep -vE '^(MATRIX_|OPENAI_|#)' "$ENV_FILE" 2>/dev/null || true
    fi
} > "$TMP_ENV"
mv "$TMP_ENV" "$ENV_FILE"

echo "[hermes-bridge] config.yaml and .env generated for ${HICLAW_WORKER_NAME}"
